name       : bluefish
version    : 2.2.9
release    : 3
source     :
    - http://www.bennewitz.com/bluefish/stable/source/bluefish-2.2.9.tar.bz2 : 5b717b563325bc6c2b6cb2700323c93eb08f914f204b322241d21744a079f7d0
license    : GPL-3.0
component  : programming.ide
summary    : Bluefish Editor
description: Bluefish is a powerful editor targeted towards programmers and webdevelopers, with many options to write websites, scripts and programming code. Bluefish supports many programming and markup languages.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pango)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
