name       : bluefish
version    : 2.2.10
release    : 7
source     :
    - https://sourceforge.net/projects/bluefish/files/bluefish/2.2.10/bluefish-2.2.10.tar.gz/download : 040746d8bfd9373e271d07a9699d648a02c77095d6ee5f313de72e7ab48284cb
license    : GPL-3.0-or-later
component  : programming.ide
summary    : Bluefish Editor
description: |
    Bluefish is a powerful editor targeted towards programmers and webdevelopers, with many options to write websites, scripts and programming code. Bluefish supports many programming and markup languages.
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gucharmap-2.90)
setup      : |
    %configure --disable-update-databases
build      : |
    %make
install    : |
    %make_install
