name       : bluefish
version    : 2.2.8
release    : 2
source     :
    - http://www.bennewitz.com/bluefish/stable/source/bluefish-2.2.8.tar.bz2 : 32578f955cee3f43e5b3a86e2588e6a679df94438b21dcbe38e3c82282745000
license    : GPL-3.0
summary    : Bluefish Editor
description: |
    Bluefish is a powerful editor targeted towards programmers and webdevelopers, with many options to write websites, scripts and programming code. Bluefish supports many programming and markup languages. 
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pango)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gdk-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
