name       : bluefish
version    : 2.2.12
release    : 12
source     :
    - https://sourceforge.net/projects/bluefish/files/bluefish/2.2.12/bluefish-2.2.12.tar.gz/download : 948fc2921f0a67a7ce811220093a3b3dfc8021a6e3005f549373cd3402ee0f26
license    : GPL-3.0-or-later
component  : programming.ide
summary    : Bluefish Editor
description: |
    Bluefish is a powerful editor targeted towards programmers and webdevelopers, with many options to write websites, scripts and programming code. Bluefish supports many programming and markup languages.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(python3)
setup      : |
    %configure --disable-update-databases
build      : |
    %make
install    : |
    %make_install
