name       : bluefish
version    : 2.2.13
release    : 14
source     :
    - https://sourceforge.net/projects/bluefish/files/bluefish/2.2.13/bluefish-2.2.13.tar.gz/download : 1b9fc488caecc082e3ef89053104a20ecccefe01730c3ad97ce435089001beb8
license    : GPL-3.0-or-later
homepage   : https://bluefish.openoffice.nl/index.html
component  : programming.ide
summary    : Bluefish Editor
description: |
    Bluefish is a powerful editor targeted towards programmers and webdevelopers, with many options to write websites, scripts and programming code. Bluefish supports many programming and markup languages.
builddeps  :
    - pkgconfig(enchant-2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(python3)
setup      : |
    %configure --disable-update-databases
build      : |
    %make
install    : |
    %make_install
